### ISSUE TITLE
constness issue in nose tests

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.learn.mlp#8]
With the new constness initiative (see: https://github.com/bioidiap/bob.blitz/issues/6) there are some nose tests failing:
https://travis-ci.org/bioidiap/bob.learn.mlp/builds/120843870
as they try to modify values that are ``const``. Please review both the tests and also whether these values must be returned as ``const`` arrays.

**Comment by siebenkopf** [comment]
I have fixed the test, but I don't see any need, why the returned arrays should be not ``writeable``. However, making the arrays ``writeable`` would require a modification of the C++ interface, i.e.:

1. either removing the constness of the returned ``blitz::Array``'s in the Machine, e.g. https://github.com/bioidiap/bob.learn.mlp/blob/master/bob/learn/mlp/include/bob.learn.mlp/machine.h#L228

2. or making it possible to pass remove the constness of an array during binding, i.e., accept ``const blitz::Array``'s inside the functions:
https://github.com/bioidiap/bob.blitz/blob/master/bob/blitz/include/bob.blitz/cppapi.h#L216
https://github.com/bioidiap/bob.blitz/blob/master/bob/blitz/include/bob.blitz/cppapi.h#L243

I would personally prefer to have the second variant, and leave it to the bindings to decide whether a bound array actually needs to be ``const``. In this way we can still keep the C++ functionality untouched (i.e., providing a const getter function), while on the python side we can modify the internal memory. 
However, there might be side-effects in the second variant.

So, what do you think? Go with option 1, 2 or leave it as it currently is?

**Comment by anjos** [comment]
You mean, returning a copy instead? The current method returns the internal state of the machine. I'm not sure it is a good idea to make that non-const as that would allow the user to change the internal state which may cause a segmentation fault later on.

The fix you did to the test is good - follows the Zen of Python (*explicit is better than implicit*). The user must actively make a copy of the internal state before modifying it. Therefore, not changing the internal state.

**Comment by siebenkopf** [comment]
No, I mean to return a non-const view of the internal memory. 
I don't see, how you would modify the internal state of a ``numpy.array`` through python that would influence the internal state. Yes, you can change the shape of the returned ``numpy.array`` -- as long as the total number of elements doesn't change -- but this would not change the shape of the internal array:

```
>>> import bob.blitz
>>> import numpy
>>> b = bob.blitz.array((10,10), numpy.float64)
>>> n = b.as_ndarray()
>>> n[0,0] = 1
>>> print n[0,0] == b[0,0]
True
>>> n.shape = (20,5)
>>> print n.shape == b.shape
False
>>> n[0,0] = 2
>>> print n[0,0] == b[0,0]
True
>>> n.shape = (40,10)
ValueError: total size of new array must be unchanged
```

On the other hand, simply changing the values of the weights by indexing the weight matrix should be allowed. I have checked the bindings of the ``Machine`` and there is no side-effect, i.e., setting new weights will not compute other values internally, see: https://github.com/bioidiap/bob.learn.mlp/blob/master/bob/learn/mlp/cxx/machine.cpp#L379
For example, this is not the case in the GMM, as pointed out here:
https://github.com/idiap/bob/issues/220
(which actually started the whole discussion).

So, I think that we can provide access to the non-const matrices inside. Actually, we can provide additional accessor functions that return non-const arrays in the Machine header:
https://github.com/bioidiap/bob.learn.mlp/blob/master/bob/learn/mlp/include/bob.learn.mlp/machine.h

**Comment by anjos** [comment]
Very well, if you wish to do so, please go ahead. This should require an API (and package) version bump though.
